.. RST substitution definitions
.. Definitions don't support links, so this isn't helpful.


.. |implementation_repository_url| replace:: https://github.com/RSE-Sheffield/strituvad-uiss-flamegpu
.. |implementation_repository_name| replace:: RSE-Sheffield/strituvad-uiss-flamegpu
.. |docs_repository_url| replace:: https://github.com/RSE-Sheffield/strituvad-uiss-flamegpu-docs
.. |docs_repository_name| replace:: RSE-Sheffield/strituvad-uiss-flamegpu-docs
